# .github/labeler.yml

- label: "components"
  files:
    - "Components/**"

- label: "sections"
  files:
    - "Sections/**"

- label: "constants"
  files:
    - "constants/**"

- label: "assets"
  files:
    - "assets/**"

- label: "config"
  files:
    - ".github/**"
    - "package.json"
    - "tsconfig.json"
    - "eslint.config.js"
    - "postcss.config.js"
    - "vite.config.js"
    - "tailwind.config.*"

- label: "styles"
  files:
    - "**/*.css"

- label: "app"
  files:
    - "App.tsx"
    - "main.tsx"
    - "index.tsx"
