# .github/labeler.yml

- label: "frontend"
  files:
    - "src/frontend/**"

- label: "backend"
  files:
    - "src/backend/**"

- label: "docs"
  files:
    - "**/*.md"

- label: "config"
  files:
    - ".github/**"

- label: "tests"
  files:
    - "tests/**"
