name: CI Checks # this must match the required status check in GitHub settings

on:
  push:
    branches:
      - "**" # all branches
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI Checks # 👈 must match
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm test
