name: Deploy to Vercel
on:
  push:
    branches:
      - main # Only deploy when code is merged into main
  pull_request:
    branches:
      - main # Optional: preview deploys for PRs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build project
        run: npm run build

      # --- Vercel Deployment ---
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Add this in your GitHub repo settings
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Add this in your GitHub repo settings
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Add this in your GitHub repo settings
          working-directory: ./
          vercel-args: "--prod" # deploy to production
